const DB=window.BIBLE_DATA;const KEY='bible-memory-v5';
const $=id=>document.getElementById(id);let state=load();let draftSegments=[];let activeRange=null;let verses=[];let verseIndex=0;let showAnswer=false;let calCursor=new Date(new Date().getFullYear(),new Date().getMonth(),1);let selectedDay=dateKey(new Date());
function load(){try{return normalize(JSON.parse(localStorage.getItem(KEY)||'{}'))}catch{return normalize({})}}
function normalize(x){return{ranges:Array.isArray(x.ranges)?x.ranges:defaultRanges(),wrong:x.wrong||{},activity:x.activity||{},passes:x.passes||0}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));renderHome();renderWrong();renderCalendar()}
function id(){return Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
function dateKey(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function defaultRanges(){return[
{id:'preset-rev7',name:'요한계시록 7장',segments:[{book:'Rev',chapter:7,start:1,end:17}]},
{id:'preset-rev14',name:'요한계시록 14장',segments:[{book:'Rev',chapter:14,start:1,end:20}]},
{id:'preset-rev15',name:'요한계시록 15장',segments:[{book:'Rev',chapter:15,start:1,end:8}]},
{id:'preset-short',name:'지정 성구 모음',segments:[{book:'Rev',chapter:1,start:1,end:3},{book:'Rev',chapter:10,start:10,end:11},{book:'Rev',chapter:20,start:4,end:6},{book:'Rev',chapter:22,start:1,end:5},{book:'Rev',chapter:22,start:18,end:19}]}]}
function book(code){return DB.find(b=>b.code===code)}
function segLabel(s){const b=book(s.book);return `${b.name} ${s.chapter}:${s.start}${s.end!==s.start?'~'+s.end:''}`}
function flattenRange(r){let arr=[];for(const s of r.segments){const b=book(s.book),ch=b.chapters[s.chapter-1]||[];for(let v=s.start;v<=Math.min(s.end,ch.length);v++)arr.push({key:`${s.book}-${s.chapter}-${v}`,book:s.book,bookName:b.name,chapter:s.chapter,verse:v,text:ch[v-1],ref:`${b.name} ${s.chapter}:${v}`})}return arr}
function setView(v){document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.view===v));document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===v+'View'));if(v==='calendar')renderCalendar()}
document.querySelectorAll('.tab').forEach(x=>x.onclick=()=>setView(x.dataset.view));$('goRange').onclick=()=>setView('range');
function renderHome(){$('rangeCount').textContent=state.ranges.length+'개';$('wrongCount').textContent=Object.values(state.wrong).filter(x=>!x.resolved).length+'개';$('passCount').textContent=state.passes+'회';$('rangeCards').innerHTML=state.ranges.length?state.ranges.map(r=>`<article class="card"><div class="card-row"><div><h3>${esc(r.name)}</h3><p class="muted">${r.segments.map(segLabel).join(' · ')}</p></div><span>${flattenRange(r).length}절</span></div><div class="card-actions"><button class="primary start" data-id="${r.id}">시험 시작</button><button class="secondary read" data-id="${r.id}">본문 보기</button><button class="danger del" data-id="${r.id}">삭제</button></div></article>`).join(''):'<div class="panel empty">저장된 범위가 없습니다.</div>';document.querySelectorAll('.start').forEach(b=>b.onclick=()=>startRange(b.dataset.id,'typing'));document.querySelectorAll('.read').forEach(b=>b.onclick=()=>startRange(b.dataset.id,'read'));document.querySelectorAll('.del').forEach(b=>b.onclick=()=>{if(confirm('이 범위를 삭제할까요?')){state.ranges=state.ranges.filter(r=>r.id!==b.dataset.id);save()}})}
function fillBooks(){$('bookSelect').innerHTML='<optgroup label="구약">'+DB.filter(b=>b.testament==='구약').map(b=>`<option value="${b.code}">${b.name}</option>`).join('')+'</optgroup><optgroup label="신약">'+DB.filter(b=>b.testament==='신약').map(b=>`<option value="${b.code}">${b.name}</option>`).join('')+'</optgroup>';updateChapters()}
function updateChapters() {const b=book($('bookSelect').value);$('chapterSelect').innerHTML=b.chapters.map((_,i)=>`<option value="${i+1}">${i+1}장</option>`).join('');updateVerses()}
function updateVerses(){const b=book($('bookSelect').value),ch=Number($('chapterSelect').value),n=b.chapters[ch-1].length;const opts=Array.from({length:n},(_,i)=>`<option value="${i+1}">${i+1}절</option>`).join('');$('startVerse').innerHTML=opts;$('endVerse').innerHTML=opts;$('endVerse').value=n}
$('bookSelect').onchange=updateChapters;$('chapterSelect').onchange=updateVerses;
$('addSegment').onclick=()=>{const s={book:$('bookSelect').value,chapter:+$('chapterSelect').value,start:+$('startVerse').value,end:+$('endVerse').value};if(s.start>s.end)[s.start,s.end]=[s.end,s.start];draftSegments.push(s);renderSegments()}
function renderSegments(){$('segmentList').innerHTML=draftSegments.map((s,i)=>`<div class="segment"><span>${esc(segLabel(s))}</span><button class="danger remove-seg" data-i="${i}">삭제</button></div>`).join('');document.querySelectorAll('.remove-seg').forEach(b=>b.onclick=()=>{draftSegments.splice(+b.dataset.i,1);renderSegments()})}
$('saveRange').onclick=()=>{const name=$('rangeName').value.trim();if(!name)return alert('범위 이름을 입력하세요.');if(!draftSegments.length)return alert('구간을 한 개 이상 추가하세요.');state.ranges.push({id:id(),name,segments:structuredClone(draftSegments)});$('rangeName').value='';draftSegments=[];renderSegments();save();setView('home')}
function startRange(rid,mode){activeRange=state.ranges.find(r=>r.id===rid);if(!activeRange)return;verses=flattenRange(activeRange);verseIndex=0;showAnswer=false;$('modeSelect').value=mode;$('studyTitle').textContent=activeRange.name;$('studyToolbar').classList.remove('hidden');$('studyActions').classList.toggle('hidden',mode==='read');renderStudy();setView('study')}
$('modeSelect').onchange=()=>{showAnswer=false;$('studyActions').classList.toggle('hidden',$('modeSelect').value==='read');renderStudy()};$('prevVerse').onclick=()=>{if(verseIndex>0){verseIndex--;showAnswer=false;renderStudy()}};$('nextVerse').onclick=()=>{if(verseIndex<verses.length-1){verseIndex++;showAnswer=false;renderStudy()}};
function normalizeText(s){return String(s||'').normalize('NFC').replace(/[\s.,!?，。！？·'“”"‘’():;()\[\]{}]/g,'')}
function blankHtml(text){let i=0;return text.split(/(\s+)/).map(t=>{if(/^\s+$/.test(t)||t.length<2)return esc(t);const hide=((i++*37+verseIndex*17)%100)<55;return hide?`<span class="blank-word" tabindex="0">${esc(t)}</span>`:esc(t)}).join('')}
function renderStudy(){if(!activeRange||!verses.length)return;const v=verses[verseIndex],mode=$('modeSelect').value;$('studyProgress').textContent=`${verseIndex+1}/${verses.length}`;let body=`<div class="verse-ref">${esc(v.ref)}</div>`;if(mode==='typing')body+=`<textarea id="typingInput" class="typing-input" placeholder="말씀을 토씨까지 입력하세요" autocorrect="off" spellcheck="false"></textarea><div id="resultArea"></div>`;else if(mode==='blank')body+=`<div class="verse-text">${blankHtml(v.text)}</div>`;else body+=`<div class="verse-text">${esc(v.text)}</div>`;$('studyArea').classList.remove('empty');$('studyArea').innerHTML=body;document.querySelectorAll('.blank-word').forEach(x=>x.onclick=()=>x.classList.toggle('reveal'))}
function diffChars(input,answer){const a=[...normalizeText(answer)],b=[...normalizeText(input)],m=a.length,n=b.length,dp=Array.from({length:m+1},()=>new Uint16Array(n+1));for(let i=m-1;i>=0;i--)for(let j=n-1;j>=0;j--)dp[i][j]=a[i]===b[j]?dp[i+1][j+1]+1:Math.max(dp[i+1][j],dp[i][j+1]);let i=0,j=0,exp='',got='';while(i<m||j<n){if(i<m&&j<n&&a[i]===b[j]){exp+=esc(a[i]);got+=esc(b[j]);i++;j++}else if(j<n&&(i===m||dp[i][j+1]>=dp[i+1][j])){got+=`<span class="diff-extra">${esc(b[j++])}</span>`}else if(i<m){exp+=`<span class="diff-missing">${esc(a[i++])}</span>`}}return{exp,got}}
$('checkAnswer').onclick=()=>{if(!activeRange)return;const v=verses[verseIndex],mode=$('modeSelect').value;if(mode!=='typing')return;const input=$('typingInput').value,ok=normalizeText(input)===normalizeText(v.text);const d=diffChars(input,v.text);$('resultArea').innerHTML=ok?'<div class="result-box correct">정답입니다.</div>':`<div class="result-box"><div class="wrong">일치하지 않습니다.</div><div class="diff-line"><strong>내 입력</strong><br>${d.got||'(입력 없음)'}</div><div class="diff-line"><strong>정답 기준</strong><br>${d.exp}</div><div class="answer-box"><strong>정답</strong><br>${esc(v.text)}</div></div>`;recordAttempt(v,input,ok);if(ok&&verseIndex===verses.length-1)completeRange()}
$('showAnswer').onclick=()=>{if(!activeRange)return;showAnswer=!showAnswer;const old=$('studyArea').querySelector('.answer-box.manual');if(old)old.remove();if(showAnswer){const v=verses[verseIndex],d=document.createElement('div');d.className='answer-box manual';d.innerHTML=`<strong>정답</strong><br>${esc(v.text)}`;$('studyArea').appendChild(d)}}
function recordAttempt(v,input,ok){const old=state.wrong[v.key];if(ok){if(old){old.resolved=true;old.resolvedAt=dateKey(new Date());old.lastInput=input}}else{state.wrong[v.key]={key:v.key,ref:v.ref,answer:v.text,lastInput:input,count:(old?.count||0)+1,lastWrong:dateKey(new Date()),resolved:false}}save()}
function completeRange(){const k=dateKey(new Date());state.activity[k]=state.activity[k]||{passed:[]};if(!state.activity[k].passed.some(x=>x.id===activeRange.id))state.activity[k].passed.push({id:activeRange.id,name:activeRange.name});state.passes++;save();setTimeout(()=>alert('선택한 범위의 마지막 절까지 통과했습니다. 달력에 기록했습니다.'),50)}
function renderWrong(){const filter=$('wrongFilter').value;let arr=Object.values(state.wrong).filter(x=>filter==='all'||(filter==='resolved'?x.resolved:!x.resolved)).sort((a,b)=>(b.lastWrong||'').localeCompare(a.lastWrong||'')||b.count-a.count);$('wrongList').innerHTML=arr.length?arr.map(x=>`<article class="card wrong-card ${x.resolved?'resolved':'active'}"><div class="card-row"><h3>${esc(x.ref)}</h3><strong>${x.count}회</strong></div><div class="wrong-meta"><span>최근 오답 ${x.lastWrong||'-'}</span><span>${x.resolved?'재시험 통과':'복습 필요'}</span></div><div class="answer-box"><strong>최근 입력</strong><br>${esc(x.lastInput||'(없음)')}<br><br><strong>정답</strong><br>${esc(x.answer)}</div><div class="card-actions"><button class="primary retry" data-key="${x.key}">이 절 재시험</button><button class="secondary resolve" data-key="${x.key}">${x.resolved?'복습 필요로 변경':'완료 처리'}</button></div></article>`).join(''):'<div class="panel empty">해당 오답 기록이 없습니다.</div>';document.querySelectorAll('.retry').forEach(b=>b.onclick=()=>retryVerse(b.dataset.key));document.querySelectorAll('.resolve').forEach(b=>b.onclick=()=>{state.wrong[b.dataset.key].resolved=!state.wrong[b.dataset.key].resolved;save()})}
$('wrongFilter').onchange=renderWrong;function retryVerse(key){const w=state.wrong[key],[code,ch,vs]=key.split('-');activeRange={id:'retry-'+key,name:`${w.ref} 재시험`,segments:[{book:code,chapter:+ch,start:+vs,end:+vs}]};verses=flattenRange(activeRange);verseIndex=0;$('modeSelect').value='typing';$('studyTitle').textContent=activeRange.name;$('studyToolbar').classList.remove('hidden');$('studyActions').classList.remove('hidden');renderStudy();setView('study')}
function renderCalendar(){const y=calCursor.getFullYear(),m=calCursor.getMonth();$('monthLabel').textContent=`${y}년 ${m+1}월`;const first=new Date(y,m,1),start=new Date(y,m,1-first.getDay());let html='';for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const k=dateKey(d),a=state.activity[k],cnt=a?.passed?.length||0;html+=`<button class="day ${d.getMonth()!==m?'dim':''} ${k===dateKey(new Date())?'today':''} ${k===selectedDay?'selected':''}" data-date="${k}"><span class="day-num">${d.getDate()}</span>${cnt?`<div class="dots">토씨 통과 ${cnt}</div>`:''}</button>`}$('calendarGrid').innerHTML=html;document.querySelectorAll('.day').forEach(b=>b.onclick=()=>{selectedDay=b.dataset.date;renderCalendar()});const items=state.activity[selectedDay]?.passed||[];$('dayDetail').innerHTML=`<strong>${selectedDay}</strong>${items.length?`<ul class="day-detail-list">${items.map(x=>`<li>토씨 시험 통과: ${esc(x.name)}</li>`).join('')}</ul>`:'<p class="muted">기록이 없습니다.</p>'}`}
$('prevMonth').onclick=()=>{calCursor=new Date(calCursor.getFullYear(),calCursor.getMonth()-1,1);renderCalendar()};$('nextMonth').onclick=()=>{calCursor=new Date(calCursor.getFullYear(),calCursor.getMonth()+1,1);renderCalendar()};
function online(){const on=navigator.onLine;$('netBadge').textContent=on?'온라인':'오프라인 사용 중'}window.addEventListener('online',online);window.addEventListener('offline',online);if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');fillBooks();renderHome();renderWrong();renderCalendar();online();
