const DB=window.BIBLE_DATA||[];const KEY='bible-memory-v6';const $=id=>document.getElementById(id);let state=load();let activeIndex=0,verseIndex=0,blankRate=.3,revealed=false,revealedBlanks=new Set(),typingDrafts={},typingResults={};let draftSegments=[];let calendarCursor=new Date(new Date().getFullYear(),new Date().getMonth(),1),selectedCalendarDate=dateKey(new Date());
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function id(){return Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
function dateKey(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function defaultRanges(){return[{id:'rev7',name:'요한계시록 7장',segments:[{book:'Rev',chapter:7,start:1,end:17}],defaultMode:'read'},{id:'rev14',name:'요한계시록 14장',segments:[{book:'Rev',chapter:14,start:1,end:20}],defaultMode:'blank'},{id:'rev15',name:'요한계시록 15장',segments:[{book:'Rev',chapter:15,start:1,end:8}],defaultMode:'blank'},{id:'rev1',name:'계 1:1~3',segments:[{book:'Rev',chapter:1,start:1,end:3}],defaultMode:'read'},{id:'rev10',name:'계 10:10~11',segments:[{book:'Rev',chapter:10,start:10,end:11}],defaultMode:'read'},{id:'rev20',name:'계 20:4~6',segments:[{book:'Rev',chapter:20,start:4,end:6}],defaultMode:'read'},{id:'rev22a',name:'계 22:1~5',segments:[{book:'Rev',chapter:22,start:1,end:5}],defaultMode:'read'},{id:'rev22b',name:'계 22:18~19',segments:[{book:'Rev',chapter:22,start:18,end:19}],defaultMode:'read'}]}
function normalize(x={}){return{ranges:Array.isArray(x.ranges)&&x.ranges.length?x.ranges:defaultRanges(),mastered:x.mastered||{},review:x.review||{},wrong:x.wrong||{},activity:x.activity||{},lastRange:x.lastRange||0}}
function load(){try{return normalize(JSON.parse(localStorage.getItem(KEY)||'{}'))}catch{return normalize()}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));renderAll()}
function book(code){return DB.find(b=>b.code===code)}
function segLabel(s){const b=book(s.book);return `${b?.name||s.book} ${s.chapter}:${s.start}${s.end!==s.start?'~'+s.end:''}`}
function flatten(r){let out=[];(r.segments||[]).forEach(s=>{const b=book(s.book),ch=b?.chapters?.[s.chapter-1]||[];for(let v=s.start;v<=Math.min(s.end,ch.length);v++)out.push({key:`${s.book}-${s.chapter}-${v}`,ref:`${b.name} ${s.chapter}:${v}`,num:v,text:ch[v-1]})});return out}
function setView(v){document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t.dataset.view===v));document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===v+'View'));if(v==='calendar')renderCalendar()}
document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>setView(t.dataset.view));
function renderList(){const list=$('passageList');$('passageCount').textContent=`${state.ranges.length}개`;list.innerHTML=state.ranges.map((r,i)=>{const st=state.mastered[r.id]?'mastered':state.review[r.id]?'review':'';const badge=st==='mastered'?'암기 완료':st==='review'?'복습 필요':`${flatten(r).length}절`;return `<button class="passage-item" data-i="${i}"><h3>${esc(r.name)}</h3><div class="passage-meta"><span>${esc(r.segments.map(segLabel).join(' · '))}</span><span class="mini-badge ${st}">${badge}</span></div></button>`}).join('');list.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>openStudy(+b.dataset.i))}
function updateDashboard(){const total=state.ranges.length,done=Object.keys(state.mastered).filter(k=>state.mastered[k]).length,pct=total?Math.round(done/total*100):0;$('progressTitle').textContent=`전체 ${total}개 중 ${done}개 암기 완료`;$('progressText').textContent=`완료율 ${pct}% · 오답 ${Object.values(state.wrong).filter(x=>!x.resolved).length}개`;$('progressBar').style.width=pct+'%'}
function currentRange(){return state.ranges[activeIndex]}
function currentVerses(){return flatten(currentRange()||{segments:[]})}
function openStudy(i=activeIndex,keepMode=false){if(!state.ranges.length)return;activeIndex=(i+state.ranges.length)%state.ranges.length;verseIndex=0;state.lastRange=activeIndex;localStorage.setItem(KEY,JSON.stringify(state));const r=currentRange();$('studyCategory').textContent=r.segments.map(segLabel).join(' · ');$('studyRef').textContent=r.name;if(!keepMode)$('modeSelect').value=r.defaultMode||'read';revealed=false;revealedBlanks.clear();typingResults={};renderVerses();setView('study')}
function initials(text){return text.split(/(\s+)/).map(t=>/^\s+$/.test(t)?t:[...t].map(ch=>/[가-힣]/.test(ch)?String.fromCharCode(((ch.charCodeAt(0)-44032)/588|0)*588+44032):ch).join('')).join('')}
function blankify(text,num){let idx=0;return text.split(/(\s+)/).map(t=>{if(/^\s+$/.test(t)||!t)return esc(t);const hide=((idx++*37+num*17)%100)<blankRate*100;if(!hide)return esc(t);const key=`${num}-${idx}`;const show=revealed||revealedBlanks.has(key);return `<button class="blank ${show?'revealed':''}" data-blank-key="${key}" type="button">${show?esc(t):'＿'.repeat(Math.max(2,[...t].length))}</button>`}).join('')}
function normalizeText(s){return String(s||'').normalize('NFC').replace(/[\s.,!?，。！？·'“”"‘’():;()\[\]{}]/g,'')}
function diffChars(input,answer){const a=[...normalizeText(answer)],b=[...normalizeText(input)],m=a.length,n=b.length,dp=Array.from({length:m+1},()=>new Uint16Array(n+1));for(let i=m-1;i>=0;i--)for(let j=n-1;j>=0;j--)dp[i][j]=a[i]===b[j]?dp[i+1][j+1]+1:Math.max(dp[i+1][j],dp[i][j+1]);let i=0,j=0,exp='',got='';while(i<m||j<n){if(i<m&&j<n&&a[i]===b[j]){exp+=esc(a[i]);got+=esc(b[j]);i++;j++}else if(j<n&&(i===m||dp[i][j+1]>=dp[i+1][j]))got+=`<span class="diff-extra">${esc(b[j++])}</span>`;else if(i<m)exp+=`<span class="diff-missing">${esc(a[i++])}</span>`}return{exp,got}}
function renderTyping(v){const key=v.key,res=typingResults[key],draft=typingDrafts[key]||'';let result='';if(res){const d=diffChars(draft,v.text);result=res.ok?'<div class="result-box correct">정답입니다.</div>':`<div class="result-box"><strong class="wrong">일치하지 않습니다.</strong><div class="diff-line"><strong>내 입력</strong><br>${d.got||'(입력 없음)'}</div><div class="diff-line"><strong>정답 기준</strong><br>${d.exp}</div><div class="answer-box"><strong>정답</strong><br>${esc(v.text)}</div></div>`}return `<div class="verse-row"><span class="verse-num">${v.num}</span><div style="flex:1"><textarea class="typing-input" data-key="${v.key}" placeholder="말씀을 토씨까지 적어 보세요">${esc(draft)}</textarea><button class="typing-check" data-key="${v.key}" type="button">정답 확인</button>${result}</div></div>`}
function renderVerses(){const r=currentRange(),vs=currentVerses();if(!r||!vs.length)return;const mode=$('modeSelect').value;$('difficultyArea').classList.toggle('hidden',mode!=='blank');$('typingGuide').classList.toggle('hidden',mode!=='typing');$('revealBtn').style.display=mode==='read'?'none':'';$('revealBtn').textContent=revealed?'정답 숨기기':mode==='typing'?'전체 정답 보기':'정답 보기';$('studyProgress').textContent=`${activeIndex+1}/${state.ranges.length}`;$('verseArea').classList.remove('empty-state');$('verseArea').innerHTML=vs.map(v=>{if(mode==='typing')return renderTyping(v);let body=esc(v.text);if(mode==='blank')body=blankify(v.text,v.num);if(mode==='initial')body=`<span class="initial-text">${esc(initials(v.text))}</span>${revealed?`<div class="muted" style="margin-top:7px">${esc(v.text)}</div>`:''}`;return `<div class="verse-row"><span class="verse-num">${v.num}</span><span>${body}</span></div>`}).join('')}
function recordAttempt(v,input,ok){const old=state.wrong[v.key];if(ok){if(old){old.resolved=true;old.resolvedAt=dateKey(new Date());old.lastInput=input}}else state.wrong[v.key]={key:v.key,ref:v.ref,answer:v.text,lastInput:input,count:(old?.count||0)+1,lastWrong:dateKey(new Date()),resolved:false};localStorage.setItem(KEY,JSON.stringify(state));renderWrong();updateDashboard()}
$('verseArea').addEventListener('input',e=>{const t=e.target.closest('.typing-input');if(t)typingDrafts[t.dataset.key]=t.value});$('verseArea').addEventListener('click',e=>{const b=e.target.closest('.blank');if(b){const k=b.dataset.blankKey;revealedBlanks.has(k)?revealedBlanks.delete(k):revealedBlanks.add(k);renderVerses();return}const c=e.target.closest('.typing-check');if(c){const v=currentVerses().find(x=>x.key===c.dataset.key),input=typingDrafts[v.key]||'',ok=normalizeText(input)===normalizeText(v.text);typingResults[v.key]={ok};recordAttempt(v,input,ok);renderVerses();const all=currentVerses().every(x=>typingResults[x.key]?.ok);if(all){recordActivity('typingPassed',currentRange().id);alert('선택한 범위의 토씨 시험을 통과했습니다.')}}});
function recordActivity(type,rid){const k=dateKey(new Date());state.activity[k]=state.activity[k]||{mastered:[],typingPassed:[]};if(!state.activity[k][type].includes(rid))state.activity[k][type].push(rid);localStorage.setItem(KEY,JSON.stringify(state));renderCalendar()}
$('modeSelect').onchange=()=>{revealed=false;revealedBlanks.clear();renderVerses()};document.querySelectorAll('.difficulty-btn').forEach(b=>b.onclick=()=>{blankRate=+b.dataset.rate;document.querySelectorAll('.difficulty-btn').forEach(x=>x.classList.toggle('active',x===b));revealed=false;revealedBlanks.clear();renderVerses()});$('revealBtn').onclick=()=>{revealed=!revealed;if(!revealed)revealedBlanks.clear();renderVerses()};$('masterBtn').onclick=()=>{const r=currentRange();state.mastered[r.id]=true;delete state.review[r.id];recordActivity('mastered',r.id);save()};$('reviewBtn').onclick=()=>{const r=currentRange();state.review[r.id]=true;delete state.mastered[r.id];save()};$('prevBtn').onclick=()=>openStudy(activeIndex-1,true);$('nextBtn').onclick=()=>openStudy(activeIndex+1,true);$('continueBtn').onclick=()=>openStudy(Math.min(state.lastRange,state.ranges.length-1));$('randomBtn').onclick=()=>{const pool=state.ranges.map((r,i)=>[r,i]).filter(([r])=>state.review[r.id]);openStudy((pool.length?pool:state.ranges.map((r,i)=>[r,i]))[Math.floor(Math.random()*(pool.length||state.ranges.length))][1])};
function fillBooks(){$('bookSelect').innerHTML='<optgroup label="구약">'+DB.filter(b=>b.testament==='구약').map(b=>`<option value="${b.code}">${b.name}</option>`).join('')+'</optgroup><optgroup label="신약">'+DB.filter(b=>b.testament==='신약').map(b=>`<option value="${b.code}">${b.name}</option>`).join('')+'</optgroup>';updateChapters()}
function updateChapters(){const b=book($('bookSelect').value);$('chapterSelect').innerHTML=b.chapters.map((_,i)=>`<option value="${i+1}">${i+1}장</option>`).join('');updateVersesSelect()}
function updateVersesSelect(){const b=book($('bookSelect').value),ch=+$('chapterSelect').value,n=b.chapters[ch-1].length,opts=Array.from({length:n},(_,i)=>`<option value="${i+1}">${i+1}절</option>`).join('');$('startVerse').innerHTML=opts;$('endVerse').innerHTML=opts;$('endVerse').value=n}
$('bookSelect').onchange=updateChapters;$('chapterSelect').onchange=updateVersesSelect;$('addSegment').onclick=()=>{let s={book:$('bookSelect').value,chapter:+$('chapterSelect').value,start:+$('startVerse').value,end:+$('endVerse').value};if(s.start>s.end)[s.start,s.end]=[s.end,s.start];draftSegments.push(s);renderSegments()};function renderSegments(){$('segmentList').innerHTML=draftSegments.map((s,i)=>`<div class="segment"><span>${esc(segLabel(s))}</span><button class="danger" data-i="${i}">삭제</button></div>`).join('');$('segmentList').querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>{draftSegments.splice(+b.dataset.i,1);renderSegments()})}$('saveRange').onclick=()=>{const name=$('rangeName').value.trim();if(!name)return alert('범위 이름을 입력하세요.');if(!draftSegments.length)return alert('구간을 먼저 추가하세요.');state.ranges.push({id:id(),name,segments:structuredClone(draftSegments),defaultMode:'blank'});draftSegments=[];$('rangeName').value='';renderSegments();save();setView('list')};
function renderWrong(){const f=$('wrongFilter').value,arr=Object.values(state.wrong).filter(x=>f==='all'||(f==='resolved'?x.resolved:!x.resolved)).sort((a,b)=>(b.lastWrong||'').localeCompare(a.lastWrong||'')||b.count-a.count);$('wrongList').innerHTML=arr.length?arr.map(x=>`<article class="card wrong-card"><h3>${esc(x.ref)} <span class="mini-badge ${x.resolved?'mastered':'review'}">${x.count}회</span></h3><div class="wrong-meta"><span>최근 오답 ${x.lastWrong||'-'}</span><span>${x.resolved?'재시험 통과':'복습 필요'}</span></div><div class="answer-box"><strong>최근 입력</strong><br>${esc(x.lastInput||'(없음)')}<br><br><strong>정답</strong><br>${esc(x.answer)}</div><div class="study-actions" style="margin-top:10px"><button class="primary retry" data-key="${x.key}">이 절 재시험</button><button class="secondary resolve" data-key="${x.key}">${x.resolved?'복습 필요로 변경':'완료 처리'}</button></div></article>`).join(''):'<div class="card settings-card muted">해당 오답 기록이 없습니다.</div>';$('wrongList').querySelectorAll('.retry').forEach(b=>b.onclick=()=>retryWrong(b.dataset.key));$('wrongList').querySelectorAll('.resolve').forEach(b=>b.onclick=()=>{state.wrong[b.dataset.key].resolved=!state.wrong[b.dataset.key].resolved;save()})}
function retryWrong(key){const w=state.wrong[key],[code,ch,vs]=key.split('-');state.ranges.push({id:'retry-'+Date.now(),name:`${w.ref} 재시험`,segments:[{book:code,chapter:+ch,start:+vs,end:+vs}],defaultMode:'typing',temporary:true});openStudy(state.ranges.length-1)}$('wrongFilter').onchange=renderWrong;
function rangeNameById(id){return state.ranges.find(r=>r.id===id)?.name||id}function formatDate(k){const d=new Date(k+'T00:00:00');return `${d.getFullYear()}년 ${d.getMonth()+1}월 ${d.getDate()}일`}
function renderCalendar(){const y=calendarCursor.getFullYear(),m=calendarCursor.getMonth();$('calendarTitle').textContent=`${y}년 ${m+1}월`;const first=new Date(y,m,1).getDay(),last=new Date(y,m+1,0).getDate();let html='';for(let i=0;i<first;i++)html+='<span class="calendar-cell empty"></span>';for(let d=1;d<=last;d++){const k=dateKey(new Date(y,m,d)),a=state.activity[k]||{mastered:[],typingPassed:[]};html+=`<button class="calendar-cell ${k===selectedCalendarDate?'selected':''} ${k===dateKey(new Date())?'today':''}" data-date="${k}"><span class="calendar-day">${d}</span><span class="calendar-marks">${a.mastered?.length?`<small class="calendar-mark mastered-mark">암기 ${a.mastered.length}</small>`:''}${a.typingPassed?.length?`<small class="calendar-mark typing-mark">토씨 ${a.typingPassed.length}</small>`:''}</span></button>`}$('calendarGrid').innerHTML=html;$('calendarGrid').querySelectorAll('[data-date]').forEach(b=>b.onclick=()=>{selectedCalendarDate=b.dataset.date;renderCalendar()});const a=state.activity[selectedCalendarDate]||{mastered:[],typingPassed:[]};$('selectedDateLabel').textContent=formatDate(selectedCalendarDate);$('dailySummary').innerHTML=`<section class="daily-block"><div class="daily-block-title"><strong>암기 완료</strong><span>${a.mastered?.length||0}개</span></div>${a.mastered?.length?`<ul>${a.mastered.map(x=>`<li>${esc(rangeNameById(x))}</li>`).join('')}</ul>`:'<p class="daily-empty">기록이 없습니다.</p>'}</section><section class="daily-block"><div class="daily-block-title"><strong>토씨 시험 통과</strong><span>${a.typingPassed?.length||0}개</span></div>${a.typingPassed?.length?`<ul>${a.typingPassed.map(x=>`<li>${esc(rangeNameById(x))}</li>`).join('')}</ul>`:'<p class="daily-empty">기록이 없습니다.</p>'}</section>`}
$('calendarPrevBtn').onclick=()=>{calendarCursor=new Date(calendarCursor.getFullYear(),calendarCursor.getMonth()-1,1);renderCalendar()};$('calendarNextBtn').onclick=()=>{calendarCursor=new Date(calendarCursor.getFullYear(),calendarCursor.getMonth()+1,1);renderCalendar()};$('calendarTodayBtn').onclick=()=>{const n=new Date();calendarCursor=new Date(n.getFullYear(),n.getMonth(),1);selectedCalendarDate=dateKey(n);renderCalendar()};
$('exportBtn').onclick=()=>{const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.href=url;a.download='성구암기-기록백업.json';a.click();URL.revokeObjectURL(url)};$('importInput').onchange=async e=>{try{state=normalize(JSON.parse(await e.target.files[0].text()));save();alert('기록을 불러왔습니다.')}catch{alert('올바른 백업 파일이 아닙니다.')}e.target.value=''};$('resetBtn').onclick=()=>{if(confirm('모든 범위와 학습 기록을 초기화할까요?')){state=normalize();save();openStudy(0)}};
function online(){const on=navigator.onLine;$('offlineBadge').textContent=on?'온라인':'오프라인 사용 중';$('offlineBadge').classList.toggle('offline',!on)}function renderAll(){renderList();updateDashboard();renderWrong();renderCalendar()}window.addEventListener('online',online);window.addEventListener('offline',online);if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));fillBooks();renderAll();online();
